#!/bin/bash

NPROC=8

WORKMIN=10000
WORKMAX=300000
WORKINTER=10000

OPMIN=100000
OPMAX=100000
OPINTER=100000

ITER=5

echo "WORKTIME,WORK,OPS,NPROC,ITER,LOCKS,BATCH"
for ((WORK = WORKMIN;WORK <= $WORKMAX;WORK += $WORKINTER))
do
		for ((OP = OPMIN;OP <= $OPMAX;OP += $OPINTER))
		do
				sudo prob/testbed/param --nproc $NPROC -w $WORK -o $OP -i $ITER
		done
done
