#!/bin/bash

NPROC=12

WORKMIN=10000
WORKMAX=100000
WORKINTER=10000

OPMIN=10000
OPMAX=100000
OPINTER=10000

ITER=5

echo "WORK,OPS,NPROC,ITER,LOCKS,BATCH"
for ((WORK = WORKMIN;WORK <= $WORKMAX;WORK += $WORKINTER))
do
		for ((OP = OPMIN;OP <= $OPMAX;OP += $OPINTER))
		do
				sudo prob/testbed/param --nproc $NPROC -w $WORK -o $OP -i $ITER
		done
done
